parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

when@test:
    services:
        _defaults:
            autowire: true
            autoconfigure: true
            public: true

        App\Tests\behat\Context\:
            resource: '../tests/behat/Context/*'

        Symfony\Contracts\HttpClient\HttpClientInterface:
            class: Symfony\Component\HttpClient\MockHttpClient

        test.data.storage:
            alias: 'test.storage'

        Doctrine\ORM\Tools\SchemaTool:

when@prod:
    parameters:
        .container.dumper.inline_factories: true
        debug.container.dump: false
