parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

when@test:
    services:
        Symfony\Contracts\HttpClient\HttpClientInterface:
            class: Symfony\Component\HttpClient\MockHttpClient

        test.data.storage:
            alias: 'test.storage'
            public: true

        Doctrine\ORM\Tools\SchemaTool:
            autowire: true
            public: true
