on:
  workflow_call:

name: Analyse
jobs:
    composer-audit:
        name: Audit
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Read the current used PHP Version
              id: get-php-version
              run: echo "::set-output name=version $(head -n1 .php-version)"
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ steps.get-php-version.outputs.version }}
                  tools: pecl, composer:2
                  extensions: mbstring
                  coverage: xdebug

            - name: Get composer cache directory
              id: composer-cache
              run: echo "COMPOSER_DIRECTORY=dir::$(composer config cache-files-dir)" >> $GITHUB_ENV

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                path: $COMPOSER_DIRECTORY
                key: ${{ runner.os }}-${{ matrix.php-version }}-composer-${{ hashFiles('*/composer.lock') }}
                restore-keys: ${{ runner.os }}-${{ matrix.php-version }}-composer-

            - name: Install dependencies
              run: composer install --prefer-dist --no-scripts --no-dev

            - run: composer audit
