on:
  workflow_call:

name: Lint
jobs:
  yaml:
    name: Analyse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: pecl
          extensions: mbstring
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "COMPOSER_DIRECTORY=dir::$(composer config cache-files-dir)" >> $GITHUB_ENV

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: $COMPOSER_DIRECTORY
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Lint Yaml files
        run: |
          bin/console lint:yaml --parse-tags config/ src/ 
