on:
  workflow_call:
    inputs:
      PHP_VERSION:
        type: string
        required: true

name: Analyse
jobs:
  phpstan:
    name: Analyse
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [ '8.3',"${{ inputs.PHP_VERSION }}" ]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: pecl
          extensions: mbstring
          coverage: xdebug

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        if: ${{ matrix.php-version != '8.4' }}
        run: composer install --prefer-dist --ignore-platform-req=php

      - name: Install dependencies
        if: ${{ matrix.php-version == '8.4' }}
        run: composer install --prefer-dist

      - name: PHPStan
        run: |
          composer phpstan
