name: Test

on: [push]

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [ '8.2', '8.3' ]
    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          php_extensions: xdebug
          bootstrap: tests/bootstrap.php
          testsuite: unit
          coverage_clover: clover.xml
        env:
          XDEBUG_MODE: coverage
