name: Test

on: [push]

jobs:
  unit:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306
    strategy:
      fail-fast: false
      matrix:
        php-version: [ '8.2', '8.3' ]
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          php_extensions: xdebug
          bootstrap: vendor/autoload.php
          testsuite: unit
          coverage_clover: clover.xml
        env:
          XDEBUG_MODE: coverage
