on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

name: Pipeline

env:
  PHP_VERSION: '8.4'
  RELEVANT_PHP_VERSIONS: '["8.3", "8.4"]'

#TODO: replace by env
jobs:
  Composer-Audit:
    uses: ./.github/workflows/composer-audit.yaml
    with:
      PHP_VERSION: '8.4'

  Lint-Yaml:
    needs:
      - Composer-Audit
    uses: ./.github/workflows/lint-yaml.yaml
    with:
      PHP_VERSION: '8.4'
  Doctrine-Schema:
    needs:
      - Composer-Audit
    uses: ./.github/workflows/doctrine-schema-validate.yaml
    with:
      PHP_VERSION: '8.4'
  PHPCS:
    needs:
      - Composer-Audit
    uses: ./.github/workflows/php-cs-fixer.yaml
  PHPStan:
    needs:
      - Composer-Audit
    uses: ./.github/workflows/PHPStan.yaml
    with:
      PHP_VERSIONS: '["8.3", "8.4"]'

  UnitTests:
    needs:
      - Lint-Yaml
      - Doctrine-Schema
      - PHPCS
      - PHPStan
    uses: ./.github/workflows/unit-tests.yaml
  IntegrationTests:
    needs:
      - Lint-Yaml
      - Doctrine-Schema
      - PHPCS
      - PHPStan
    uses: ./.github/workflows/integration-tests.yaml
  Behat:
    needs:
      - UnitTests
      - IntegrationTests
    uses: ./.github/workflows/Behat.yaml
    with:
      PHP_VERSIONS: '["8.3", "8.4"]'

  Setup:
    needs:
      - Behat
    uses: ./.github/workflows/setup.yaml
