on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

name: Pipeline

env:
  CURRENT_PHP_VERSION: '8.4'
  PREVIOUS_PHP_VERSION: '8.3'

jobs:
  Init:
    runs-on: ubuntu-latest
    outputs:
      CURRENT_PHP_VERSION: ${{ steps.init.outputs.CURRENT_PHP_VERSION }}
      PREVIOUS_PHP_VERSION: ${{ steps.init.outputs.PREVIOUS_PHP_VERSION }}
    steps:
      - name: Init Variables
        id: init
        run: |
          echo $CURRENT_PHP_VERSION
          echo "CURRENT_PHP_VERSION=$CURRENT_PHP_VERSION" >> $GITHUB_OUTPUT
          echo "PREVIOUS_PHP_VERSION=$PREVIOUS_PHP_VERSION" >> $GITHUB_OUTPUT

  Composer-Audit:
    needs:
      - Init
    uses: ./.github/workflows/composer-audit.yaml
    with:
      CURRENT_PHP_VERSION: ${{ needs.Init.outputs.CURRENT_PHP_VERSION }}

  Lint-Yaml:
    needs:
      - Composer-Audit
      - Init
    uses: ./.github/workflows/lint-yaml.yaml
    with:
      CURRENT_PHP_VERSION: ${{ needs.Init.outputs.CURRENT_PHP_VERSION }}
  Doctrine-Schema:
    needs:
      - Composer-Audit
      - Init
    uses: ./.github/workflows/doctrine-schema-validate.yaml
    with:
      CURRENT_PHP_VERSION: ${{ needs.Init.outputs.CURRENT_PHP_VERSION }}
  PHPCS:
    needs:
      - Composer-Audit
      - Init
    uses: ./.github/workflows/php-cs-fixer.yaml
  PHPStan:
    needs:
      - Composer-Audit
      - Init
    uses: ./.github/workflows/PHPStan.yaml
    with:
      CURRENT_PHP_VERSION: ${{ needs.Init.outputs.CURRENT_PHP_VERSION }}
      PREVIOUS_PHP_VERSION: ${{ needs.Init.outputs.PREVIOUS_PHP_VERSION }}

  UnitTests:
    needs:
      - Lint-Yaml
      - Doctrine-Schema
      - PHPCS
      - PHPStan
      - Init
    uses: ./.github/workflows/unit-tests.yaml
    with:
      CURRENT_PHP_VERSION: ${{ needs.Init.outputs.CURRENT_PHP_VERSION }}
      PREVIOUS_PHP_VERSION: ${{ needs.Init.outputs.PREVIOUS_PHP_VERSION }}
  IntegrationTests:
    needs:
      - Lint-Yaml
      - Doctrine-Schema
      - PHPCS
      - PHPStan
      - Init
    uses: ./.github/workflows/integration-tests.yaml
    with:
      CURRENT_PHP_VERSION: ${{ needs.Init.outputs.CURRENT_PHP_VERSION }}
      PREVIOUS_PHP_VERSION: ${{ needs.Init.outputs.PREVIOUS_PHP_VERSION }}
  Behat:
    needs:
      - UnitTests
      - IntegrationTests
      - Init
    uses: ./.github/workflows/Behat.yaml
    with:
      CURRENT_PHP_VERSION: ${{ needs.Init.outputs.CURRENT_PHP_VERSION }}
      PREVIOUS_PHP_VERSION: ${{ needs.Init.outputs.PREVIOUS_PHP_VERSION }}

  Setup:
    needs:
      - Behat
    uses: ./.github/workflows/setup.yaml
