on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

name: Pipeline

env:
  PHP_VERSION: '8.4'

jobs:
  Init:
    steps:
      - name: Set env BRANCH
        run: echo "PHP_VERSION="8.4" >> $GITHUB_ENV
    runs-on: ubuntu-latest

  Composer-Audit:
    uses: ./.github/workflows/composer-audit.yaml

  Lint-Yaml:
    needs:
      - Composer-Audit
    uses: ./.github/workflows/lint-yaml.yaml
  Doctrine-Schema:
    needs:
      - Composer-Audit
    uses: ./.github/workflows/doctrine-schema-validate.yaml
  PHPCS:
    needs:
      - Composer-Audit
    uses: ./.github/workflows/php-cs-fixer.yaml
  PHPStan:
    needs:
      - Composer-Audit
    uses: ./.github/workflows/PHPStan.yaml

  UnitTests:
    needs:
      - Lint-Yaml
      - Doctrine-Schema
      - PHPCS
      - PHPStan
    uses: ./.github/workflows/unit-tests.yaml
  IntegrationTests:
    needs:
      - Lint-Yaml
      - Doctrine-Schema
      - PHPCS
      - PHPStan
    uses: ./.github/workflows/integration-tests.yaml
  Behat:
    needs:
      - UnitTests
      - IntegrationTests
    uses: ./.github/workflows/Behat.yaml

  Setup:
    needs:
      - Behat
    uses: ./.github/workflows/setup.yaml
