on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

name: Pipeline

env:
  CURRENT_PHP_VERSION: '8.4'
  PREVIOUS_PHP_VERSION: '8.3'

jobs:
  Init:
    runs-on: ubuntu-latest
    steps:
      - name: Get URL env var
        id: init
        run: |
          echo $CURRENT_PHP_VERSION
          echo "PHP_VERSION=$CURRENT_PHP_VERSION" >> $GITHUB_OUTPUT

  Composer-Audit:
    uses: ./.github/workflows/composer-audit.yaml
    with:
      CURRENT_PHP_VERSION: "${{ jobs.Init.steps.init.outputs.dir }}"

  Lint-Yaml:
    needs:
      - Composer-Audit
    uses: ./.github/workflows/lint-yaml.yaml
    with:
      CURRENT_PHP_VERSION: '8.4'
  Doctrine-Schema:
    needs:
      - Composer-Audit
    uses: ./.github/workflows/doctrine-schema-validate.yaml
    with:
      CURRENT_PHP_VERSION: '8.4'
  PHPCS:
    needs:
      - Composer-Audit
    uses: ./.github/workflows/php-cs-fixer.yaml
  PHPStan:
    needs:
      - Composer-Audit
    uses: ./.github/workflows/PHPStan.yaml
    with:
      CURRENT_PHP_VERSION: '8.4'
      PREVIOUS_PHP_VERSION: '8.3'

  UnitTests:
    needs:
      - Lint-Yaml
      - Doctrine-Schema
      - PHPCS
      - PHPStan
    uses: ./.github/workflows/unit-tests.yaml
    with:
      CURRENT_PHP_VERSION: '8.4'
      PREVIOUS_PHP_VERSION: '8.3'
  IntegrationTests:
    needs:
      - Lint-Yaml
      - Doctrine-Schema
      - PHPCS
      - PHPStan
    uses: ./.github/workflows/integration-tests.yaml
    with:
      CURRENT_PHP_VERSION: '8.4'
      PREVIOUS_PHP_VERSION: '8.3'
  Behat:
    needs:
      - UnitTests
      - IntegrationTests
    uses: ./.github/workflows/Behat.yaml
    with:
      CURRENT_PHP_VERSION: '8.4'
      PREVIOUS_PHP_VERSION: '8.3'

  Setup:
    needs:
      - Behat
    uses: ./.github/workflows/setup.yaml
