on: [push]
name: Test
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Docker Universe
        run: docker compose -f docker-compose.prod.yaml up --build -d

      - name: Debug
        run: |
          docker compose wait setup-php
          docker compose wait setup-db
          chmod -R 777 ./var

      - name: Debug
        run: curl -I http://localhost:8080/api/currencies/USD

      - name: Debug
        run: ls -la var/cache
      - name: Debug
        run: ls -la var/log

      - uses: mydea/action-wait-for-api@v1
        with:
          url: "http://localhost:8080/api/currencies/USD"
          expected-response-field: "iso3"
          expected-response-field-value: "USD"

      - name: Check api resource (Currencies)
        uses: TobiasOlofsson88/github-action-validate-json-request-result@v1.0.5
        with:
          request-method: "GET"
          request-url: "http://localhost:8080/api/currencies"
          validate-expression: "response.length > 10 && response[0].attribute == 'value'"

      - name: Check api resource (Currency)
        uses: TobiasOlofsson88/github-action-validate-json-request-result@v1.0.5
        with:
          request-method: "GET"
          request-url: "http://localhost:8080/api/currencies/USD"
          validate-expression: "response.iso3 == 'USD'"

      - name: Check api docs
        run: curl -I http://localhost:8080/api/docs

      - name: Check api resource (history)
        run: |
          curl -I http://localhost:8080/api/currencies
          curl -I http://localhost:8080/api/currencies/USD
          curl -I http://localhost:8080/api/currencies/USD/history
