on: [push]
name: Test
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Docker Universe
        run: docker compose -f docker-compose.prod.yaml up --build -d --wait --wait-timeout 60

      - name: Check api docs
        run: curl -I http://localhost:8080/api/docs

      - name: Check api resources
        run: |
          curl -s http://localhost:8080/api/currencies
          curl -s http://localhost:8080/api/currencies/USD
          curl -s http://localhost:8080/api/currencies/USD/history
