on:
  workflow_call:

name: Test
jobs:
  setup:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Docker images
        uses: ScribeMD/docker-cache@0.3.6
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('docker-compose.prod.yaml') }}

      - name: Create Docker Universe
        run: docker compose -f docker-compose.prod.yaml up --build -d

      - name: Wait for setup
        run: |
          docker compose wait setup-php
          docker compose wait setup-db
          sudo chmod -R 777 ./var

      - uses: mydea/action-wait-for-api@v1
        with:
          url: "http://localhost:8080/api/currencies/USD"
          expected-response-field: "iso3"
          expected-response-field-value: "USD"

      - name: Check api docs
        run: curl -I http://localhost:8080/api/docs

      - name: Check api resources
        run: |
          curl -I http://localhost:8080/api/currencies 
          curl -I http://localhost:8080/api/currencies/USD
          curl -I http://localhost:8080/api/currencies/USD/history

      - name: Validate JSON
        run: |
          curl http://localhost:8080/api/currencies | jq
          curl http://localhost:8080/api/currencies/USD | jq
          curl http://localhost:8080/api/currencies/USD/history | jq
