on:
  workflow_call:

name: Test

jobs:
  unit:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [ '8.3', '8.4' ]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: pecl
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "COMPOSER_DIRECTORY=dir::$(composer config cache-files-dir)" >> $GITHUB_ENV

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: $COMPOSER_DIRECTORY
          key: ${{ runner.os }}-${{ matrix.php-version }}-composer-${{ hashFiles('*/composer.lock') }}

      - name: Install dependencies
        if: ${{ matrix.php-version != '8.4' }}
        run: composer install --prefer-dist --ignore-platform-req=php

      - name: Install dependencies
        if: ${{ matrix.php-version == '8.4' }}
        run: composer install --prefer-dist

      - name: run Tests
        run: vendor/bin/phpunit --testsuite unit
